apiVersion: v1
kind: Pod
metadata:
  name: montecarloavx512
  labels:
    name: montecarloavx512
spec:
  restartPolicy: Never
  nodeSelector:
    node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX512BW: "true"
    kubernetes.io/hostname: k8s-node1
  containers:
  - name: montecarlo
    image: ptorre/montecarlo
    imagePullPolicy: Always
    command: ["/app/start"]
#    command: ["sleep", "infinity"]
    env:
    - name: PR
      value: "8"
    - name: USE_AVX512
      value: "1"
    - name: PUSHGWIP
      value: "192.168.0.235"
    resources:
      requests:
        memory: "500Mi"
        cpu: "8"
      limits:
        memory: "500Mi"
        cpu: "8"